### ISSUE TITLE
Add support for creating new in proceedings references

### ISSUE THREAD

**Issue by impliedfeline** [ScrumMestarit/BibTeXt#22]
As a user
I want to be able to create new in proceeding references
so that I can cite proceedings

**Tasks:**
- [x] Generate new in proceedings reference model
- [x] Validate new in proceedings reference fields
- [x] Add new table to page for in proceedings references
- [x] BDD tests
- [x] Unit tests

**Confirmations:**
- User can add new in proceedings reference
- Reference may be viewed in the page view

**Comment by impliedfeline** [comment]
Tables and tests implemented in 89b8773 and d07c4ef respectively.
