### ISSUE TITLE
Add support for creating new book references

### ISSUE THREAD

**Issue by JaakkoLipsanen** [ScrumMestarit/BibTeXt#4]
As a user
I want to be able to create new book references
so that I can cite books

**Tasks:**
- [x] Generate new book reference model
- [x] Validate new book reference fields
- [x] Add new table to page for book references
- [x] BDD tests
- [x] Unit tests

**Confirmations:**
- User can add new book reference
- Reference may be viewed in the page view

**Comment by impliedfeline** [comment]
Tables and tests implemented in 89b8773 and d07c4ef respectively.
